#!/usr/bin/env node
/**
 * Patches Prisma client files to support WASM engine loading in standard Node.js.
 *
 * WHY: On ARM64 Windows with native ARM64 Node.js, Prisma's x64 library binary
 * cannot be loaded. The WASM engine is the correct fallback, but the default
 * wasm-worker-loader.mjs uses `import('./query_engine_bg.wasm')` which returns
 * a module *namespace* in Node.js – it has no `.default` export, so Prisma
 * receives `undefined` and throws "wasm module unexpectedly null".
 *
 * FIX: We create a `wasm-node-loader.mjs` that reads the WASM bytes via fs and
 * compiles them with WebAssembly.compile(), which returns a proper
 * WebAssembly.Module. We then register it as the `node` condition in
 * .prisma/client/package.json imports.
 *
 * Run after `prisma generate`. Hooked into the prisma:generate and setup scripts
 * in package.json so it re-applies whenever the generated client is refreshed.
 */

const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const dotPrismaDir = path.join(root, "node_modules/.prisma/client");

if (!fs.existsSync(dotPrismaDir)) {
  console.log(
    "⚠  .prisma/client not found – run `npx prisma generate` first, then re-run this script."
  );
  process.exit(0);
}

// ── Fix 1: Node.js-compatible WASM engine loader ─────────────────────────────
// The default wasm-worker-loader.mjs does:
//   export default import('./query_engine_bg.wasm')
// In Node.js, dynamic import() of a .wasm file yields a module namespace with
// named exports from the WASM binary – there is no `.default`. Prisma expects
// `.default` to be a WebAssembly.Module, so it gets undefined and crashes.
//
// Our replacement reads the bytes with readFileSync and compiles them to a real
// WebAssembly.Module, then exports in the same shape Prisma expects:
//   Promise<{ default: WebAssembly.Module }>
const nodeLoaderContent = `// Auto-generated by scripts/patch-prisma.js — do not edit manually.
// Node.js-compatible WASM engine loader for Prisma.
// Uses fs.readFileSync + WebAssembly.compile() instead of import('./file.wasm'),
// which does not expose a .default export in standard Node.js.
import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
const __dir = dirname(fileURLToPath(import.meta.url));
const buf = readFileSync(join(__dir, 'query_engine_bg.wasm'));
const mod = await WebAssembly.compile(buf);
// Mirror the Cloudflare Workers import() shape: Promise<{ default: WebAssembly.Module }>
export default Promise.resolve({ default: mod });
`;

fs.writeFileSync(path.join(dotPrismaDir, "wasm-node-loader.mjs"), nodeLoaderContent);
console.log("✓ Created .prisma/client/wasm-node-loader.mjs");

// ── Fix 2: Register the loader for the `node` condition ──────────────────────
const pkgPath = path.join(dotPrismaDir, "package.json");
try {
  const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
  const loaders = pkg.imports?.["#wasm-engine-loader"];
  if (!loaders) {
    console.warn("⚠  Could not find #wasm-engine-loader in .prisma/client/package.json – skipping.");
  } else if (loaders.node === "./wasm-node-loader.mjs") {
    console.log("ℹ  .prisma/client/package.json already has the node condition – no change needed.");
  } else {
    // Insert `node` as the first/highest-priority condition
    pkg.imports["#wasm-engine-loader"] = {
      node: "./wasm-node-loader.mjs",
      ...loaders,
    };
    fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n");
    console.log("✓ Patched .prisma/client/package.json (node → wasm-node-loader.mjs)");
  }
} catch (e) {
  console.warn("⚠  Could not patch .prisma/client/package.json:", e.message);
}

console.log("\nPrisma ARM64-compat patches applied successfully.\n");
