api_version = "2026-01"

[[extensions]]
type = "ui_extension"
# Change the merchant-facing name of the extension in locales/en.default.json
name = "t:name"
uid = "b782b75a-7d98-79a1-c592-f9cc2ac8210e6abc36de"
handle = "requests-pos"
description = "Customer special-order requests and inventory matches on POS"

# module: file that contains your extension’s source code
# target: location where your extension appears in POS
[[extensions.targeting]]
module = "./src/Tile.jsx"
target = "pos.home.tile.render"

[[extensions.targeting]]
module = "./src/Modal.jsx"
target = "pos.home.modal.render"
